"use client";

import React, { useState } from "react";
import Link from "next/link";
import { ChevronDown, HelpCircle, ArrowRight } from "lucide-react";

export const FAQSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      q: "How long does it take to complete a business plan or financing package?",
      a: "Our standard turnaround time is 5 to 7 business days from the moment we receive your completed intake questionnaire and supporting documents. Expedited delivery options (48 to 72 hours) are available for urgent lender deadlines.",
    },
    {
      q: "Which lenders do you write documents for?",
      a: "We write business plans, financial models, and loan packages tailored to the underwriting standards of BDC (Business Development Bank of Canada), CSBFL lenders (all major chartered banks and credit unions), Farm Credit Canada (FCC), Export Development Canada (EDC), private lenders, venture capital funds, and government grant programs across Canada.",
    },
    {
      q: "What is the difference between a business plan written by BigPlans.ca and one generated by AI or a generic template?",
      a: "Generic templates and AI generators produce superficial text without real financial modeling, lender-specific risk analysis, or institutional compliance. Our packages are crafted by experienced credit analysts, include dynamic 36-month pro forma financial models, and directly address the specific underwriting criteria credit officers evaluate.",
    },
    {
      q: "Do you guarantee that my loan or financing application will be approved?",
      a: "No firm can guarantee lender approval, as final credit decisions depend on factors beyond documentation — such as borrower credit history, collateral quality, and lender risk appetite. However, we guarantee that your documentation package will meet or exceed institutional underwriting standards, eliminating paperwork-related declines.",
    },
    {
      q: "What information do I need to provide to get started?",
      a: "During your free initial consultation, we will review your business concept, target funding amount, and intended lender. We then provide a streamlined intake checklist covering your business history, target market, operational model, management background, and intended use of funds.",
    },
  ];

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="bg-paper-dark py-16 md:py-24 border-b border-ink-10">
      <div className="max-w-4xl mx-auto px-4 sm:px-6">
        <div className="text-center max-w-2xl mx-auto mb-14">
          <span className="text-xs font-bold uppercase tracking-widest text-electric block mb-2">
            Clear Answers
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-ink">
            Frequently Asked Questions
          </h2>
          <p className="text-ink-70 text-base mt-2">
            Everything you need to know about our business plans, financial modeling, and lender packages.
          </p>
        </div>

        {/* Accordion List */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className="bg-paper rounded-card border border-ink-10 overflow-hidden shadow-sm transition-all"
              >
                <button
                  onClick={() => toggleFAQ(idx)}
                  className="w-full p-6 text-left font-bold text-ink hover:text-electric flex items-center justify-between gap-4 transition-colors focus:outline-none focus:ring-2 focus:ring-electric"
                  aria-expanded={isOpen}
                >
                  <span className="text-base sm:text-lg">{faq.q}</span>
                  <div
                    className={`w-8 h-8 rounded-full bg-electric-10 flex items-center justify-center text-electric shrink-0 transition-transform duration-200 ${
                      isOpen ? "rotate-180 bg-electric text-white" : ""
                    }`}
                  >
                    <ChevronDown size={18} />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-6 pb-6 pt-0 text-ink-70 text-sm sm:text-base leading-relaxed border-t border-ink-10/40 mt-2 animate-fadeIn">
                    <p className="pt-4">{faq.a}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        <div className="mt-10 text-center text-xs font-semibold text-ink-40">
          Have a question not listed here?{" "}
          <Link href="/contact" className="text-electric hover:underline font-bold">
            Contact our advisory team directly
          </Link>
        </div>
      </div>
    </section>
  );
};
